### PR TITLE
Update OctoPrint plugin in README.md

### PR DESCRIPTION
**Pull request by zarthross**
original plugins repo was archived, putting in new link found from Octoprint plugin site

https://plugins.octoprint.org/plugins/Spoolman/

### CODE REVIEW

**Comment by zarthross** [comment]
Maybe I should mark it as long longer in progress?  I haven't tested it myself, but its at 1.x.x release.

**Comment by Donkie** [comment]
Amazing, didn't know this existed!
Yes, please remove the in progress.

**Comment by zarthross** [comment]
Done!

**Comment by Donkie** [comment]
Perfect, thank you :)

**Pull request merged**
