### PR TITLE
Added td value for spool

### PR DESCRIPTION
**Pull request by mawoka-myblock**
Addresses #235

### CODE REVIEW

**Comment by mawoka-myblock** [comment]
The following error appears when trying to view a spool:
```
INFO:     127.0.0.1:47534 - "GET /spool/1 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/mawoka/PycharmProjects/Spoolman/.venv/lib/python3.11/site-packages/fastapi/encoders.py", line 230, in jsonable_encoder
    data = dict(obj)
           ^^^^^^^^^
TypeError: 'FieldInfo' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mawoka/PycharmProjects/Spoolman/.venv/lib/python3.11/site-packages/fastapi/encoders.py", line 235, in jsonable_encoder
    data = vars(obj)
           ^^^^^^^^^
TypeError: vars() argument must have __dict__ attribute

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mawoka/PycharmProjects/Spoolman/.venv/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 435, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mawoka/PycharmProjects/Spoolman/.venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mawoka/PycharmProjects/Spoolman/.venv/lib/python3.11/site-packages/fastapi/applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "/home/mawoka/PycharmProjects/Spoolman/.venv/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/mawoka/PycharmProjects/Spoolman/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/mawoka/PycharmProjects/Spoolman/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/mawoka/PycharmProjects/Spoolman/.venv/lib/python3.11/site-packages/starlette/middleware/cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/mawoka/PycharmProjects/Spoolman/.venv/lib/python3.11/site-packages/starlette/middleware/cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "/home/mawoka/PycharmProjects/Spoolman/.venv/lib/python3.11/site-packages/starlette/middleware/gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "/home/mawoka/PycharmProjects/Spoolman/.venv/lib/python3.11/site-packages/starlette/middleware/gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/home/mawoka/PycharmProjects/Spoolman/.venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/mawoka/PycharmProjects/Spoolman/.venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/mawoka/PycharmProjects/Spoolman/.venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/mawoka/PycharmProjects/Spoolman/.venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/mawoka/PycharmProjects/Spoolman/.venv/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/mawoka/PycharmProjects/Spoolman/.venv/lib/python3.11/site-packages/starlette/routing.py", line 443, in handle
    await self.app(scope, receive, send)
  File "/home/mawoka/PycharmProjects/Spoolman/.venv/lib/python3.11/site-packages/fastapi/applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "/home/mawoka/PycharmProjects/Spoolman/.venv/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/mawoka/PycharmProjects/Spoolman/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/mawoka/PycharmProjects/Spoolman/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/mawoka/PycharmProjects/Spoolman/.venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/mawoka/PycharmProjects/Spoolman/.venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/mawoka/PycharmProjects/Spoolman/.venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/mawoka/PycharmProjects/Spoolman/.venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/mawoka/PycharmProjects/Spoolman/.venv/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/mawoka/PycharmProjects/Spoolman/.venv/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/mawoka/PycharmProjects/Spoolman/.venv/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/mawoka/PycharmProjects/Spoolman/.venv/lib/python3.11/site-packages/fastapi/routing.py", line 291, in app
    content = await serialize_response(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mawoka/PycharmProjects/Spoolman/.venv/lib/python3.11/site-packages/fastapi/routing.py", line 169, in serialize_response
    return jsonable_encoder(
           ^^^^^^^^^^^^^^^^^
  File "/home/mawoka/PycharmProjects/Spoolman/.venv/lib/python3.11/site-packages/fastapi/encoders.py", line 143, in jsonable_encoder
    return jsonable_encoder(
           ^^^^^^^^^^^^^^^^^
  File "/home/mawoka/PycharmProjects/Spoolman/.venv/lib/python3.11/site-packages/fastapi/encoders.py", line 195, in jsonable_encoder
    encoded_value = jsonable_encoder(
                    ^^^^^^^^^^^^^^^^^
  File "/home/mawoka/PycharmProjects/Spoolman/.venv/lib/python3.11/site-packages/fastapi/encoders.py", line 209, in jsonable_encoder
    jsonable_encoder(
  File "/home/mawoka/PycharmProjects/Spoolman/.venv/lib/python3.11/site-packages/fastapi/encoders.py", line 238, in jsonable_encoder
    raise ValueError(errors) from e
ValueError: [TypeError("'FieldInfo' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]
```

And i don't know why. Maybe @Donkie, could you help me finding the reason why this error appears?

**Comment by mawoka-myblock** [comment]
To fix this error, I am not returning the whole model, just the dictionary of it. I wouldn't mind, but you may.

**Comment by Donkie** [comment]
Thank you for your contribution, I highly appreciate it. However, this transmission distance is a somewhat niche field, and I don't want to add any more such fields as a pure database column. Instead, it should be part of "user custom fields" as described in issue #242 . That way, we can let users create any fields they want, and the UI wouldn't be cluttered up with fields most people aren't using.

**Comment by mawoka-myblock** [comment]
Would it be an option to merge this PR and have this column until we get these custom fields? I'd also happily write a database migration for the transition in the future.

**Comment by Donkie** [comment]
I'll let this rest here for a few days, and if I haven't implemented custom fields by then I will merge this.
I'm working on custom fields right now.

**Comment by mawoka-myblock** [comment]
> I'll let this rest here for a few days, and if I haven't implemented custom fields by then I will merge this. I'm working on custom fields right now.

Ah, okay! Then: Good luck and thank you for your awesome project!

**Comment by mawoka-myblock** [comment]
Sure! Did you find out why I couldn't just return the class, but had to return the dict of it? Really curious, since I am also using fastapi in my own projects. If you haven't looked at it, I completely understand that.

**Pull request closed without merging**
