### PR TITLE
Russian translation updated

### PR DESCRIPTION
**Pull request by DrPerryCoke**

### CODE REVIEW

**Comment by Donkie** [comment]
Please use weblate instead

https://hosted.weblate.org/projects/spoolman/web-client/

**Comment by DrPerryCoke** [comment]
> Please use weblate instead
> 
> https://hosted.weblate.org/projects/spoolman/web-client/

I just learned to use GitHub, but here’s something new)))
What should we do about this?

**Comment by Donkie** [comment]
> > Please use weblate instead
> > https://hosted.weblate.org/projects/spoolman/web-client/
> 
> I just learned to use GitHub, but here’s something new))) What should we do about this?

Yes I recently started using Weblate for Spoolman for translations since it's a simpler and more powerful tool for translators. Just make an account at weblate and then go to the link I sent you. There you can open up the Russian language and work on the translations.

**Comment by DrPerryCoke** [comment]
> > > Please use weblate instead
> > > https://hosted.weblate.org/projects/spoolman/web-client/
> > 
> > 
> > I just learned to use GitHub, but here’s something new))) What should we do about this?
> 
> Yes I recently started using Weblate for Spoolman for translations since it's a simpler and more powerful tool for translators. Just make an account at weblate and then go to the link I sent you. There you can open up the Russian language and work on the translations.

I meant with this pull request)

**Comment by Donkie** [comment]
Ah, sorry. Please re-do these changes in weblate instead, it's simpler for me that way.

**Pull request closed without merging**
