### PR TITLE
add text field with placeholders for custom label format

### PR DESCRIPTION
**Pull request by TomW1605**
implement #78 and #231

this still needs some work.

- [ ] there are some translation strings that need to be added (i will do english, not sure about the others)
- [x] need to add some filtering to only allow a set of html tags
- [x] need to localise the number format functions (eg, use the right money symbol and `.`/`,`)
- [x] need to add a date format function
- [ ] need to add an expandable list of placeholders with examples (also want to make it so if you click one it will be inserted into the text)
- [ ] need to add explanation/examples of how the conditional prefix/suffixes work
- [ ] work out how to handle extra fields

### CODE REVIEW

**Comment by Donkie** [comment]
Closing this since I have now implemented a template system myself, which will be available in the next release.
It doesn't have as many fancy formatting ideas as you had here, but that could be added later :)

Thank you for your attempt anyway!

**Comment by TomW1605** [comment]
thats great.

i have had a look at your implementation and i dont think it would be hard to adapt my extra formatting options to the way you are doing it. if your open to it i will take a look at some point this weekend

**Comment by Donkie** [comment]
Yes feel free

**Comment by TomW1605** [comment]
i have tried a few different methods but im thinking that the easiest option is probably to use a standard markdown library such as  [react-markdown](https://github.com/remarkjs/react-markdown) for the actual formatting from the markdown to the react components. would that be ok with you?

**Comment by TomW1605** [comment]
i got it working with react-markdown. there are still a few quirks i want to iron out (mostly around it not seeming to like new lines that are not full new paragraphs that take up way too much room) but i think that should be easy compared to writing from scratch

i also got the pre/post fix stuff working again, in a way that it will also be backwards compatable (ie, if you dont use it you only need a single `{}` pair)

**Pull request closed without merging**
